<?php

namespace EvenementBundle\Repository;

/**
 * participationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWhatYouWant1($yarab)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('identity(u.idEvent)')
            ->where('u.idMembre = :identifier')
            ->setParameter('identifier', $yarab);

        return $qb->getQuery()
            ->getResult();
    }
}
